package com.voiture.v1.enums;

public enum Typemaintenance {
    // Maintenances mécaniques de base
    VIDANGE,
    REVISION_PERIODIQUE,
    FREINS,
    PNEUS,
    BATTERIE,
    CLIMATISATION,
    SUSPENSION,
    DIRECTION,
    TRANSMISSION,
    EMBRAYAGE,
    ECHAPPEMENT,
    CARROSSERIE,
    PHARES,
    ESSUIE_GLACES,
    LIQUIDES,
    DIAGNOSTIC,
    REPARATION_ELECTRIQUE,
    REPARATION_MOTEUR,
    NETTOYAGE_INTERIEUR,
    LAVAGE_EXTERIEUR,

    // Charges liées à l'assurance
    ASSURANCE_RESPONSABILITE_CIVILE,
    ASSURANCE_TOUS_RISQUES,
    ASSURANCE_BRIS_DE_GLACE,
    ASSURANCE_VOL,
    ASSURANCE_INCENDIE,
    ASSURANCE_CATASTROPHE_NATURELLE,
    FRANCHISE_ASSURANCE,
    RENOUVELLEMENT_ASSURANCE,

    // Charges administratives
    CARTE_GRISE,
    VIGNETTE,
    CONTROLE_TECHNIQUE,
    TAXE_VEHICULE,
    CERTIFICAT_IMMATRICULATION,

    // Charges liées aux consommables
    CARBURANT,
    HUILE_MOTEUR,
    LIQUIDE_FREIN,
    LIQUIDE_REFROIDISSEMENT,
    LIQUIDE_LAVE_GLACE,
    FILTRE_HUILE,
    FILTRE_AIR,
    FILTRE_CARBURANT,
    FILTRE_HABITACLE,

    // Charges liées aux pièces d'usure
    PLAQUETTES_FREIN,
    DISQUES_FREIN,
    AMORTISSEURS,
    COURROIE_DISTRIBUTION,
    BOUGIES_ALLUMAGE,
    BALAIS_ESSUIE_GLACE,
    AMPOULES,
    BATTERIE_REMPLACEMENT,

    // Charges liées aux réparations spécifiques
    REPARATION_PARE_BRISE,
    REPARATION_CARROSSERIE,
    REPARATION_ALTERNATEUR,
    REPARATION_DEMARREUR,
    REPARATION_POMPE_A_EAU,
    REPARATION_POMPE_A_CARBURANT,
    REPARATION_TURBO,
    REPARATION_BOITE_VITESSE,

    // Charges liées au stationnement et infractions
    STATIONNEMENT,
    CONTRAVENTION,
    MISE_EN_FOURRIERE,

    // Autres charges diverses
    DEPANNAGE,
    REMORQUAGE,
    LAVAGE_PROFESSIONNEL,
    DETAILING,
    AUTRE;
}
